var quotes = [
    "This sentence is not recursive, yet.",
    "This is the second sentence that has yet to be recurive.",
    "This sentence no verb.",
    "This sentence is false.",
    "do you know of great GEB-ish / self-ref jokes?",
    "s is a sentence with no subject is a sentence with no subject.",
    "This sentence totally fails in its attempt to convey the point that it is not trying to make.",
    "What do \"masochism\" and \"amnesia\" mean?",
    "Beats me! I forget!",
    "What is the difference between ignorance and apathy?",
    "I don't know and I don't care!",
    "I'm not me!",
    "Don't use contractions.",
    "The first, eighth, thirteenth, fifteenth, nineteenth, twenty-third, twenty-eighth, thirty-second, thirty-eighth, .....",
    "Try not to ever split infinitives.",
    "Always proofread to make sure you didn't any words out.",
    "This sentence is meaningless because it is self-referential.",
    "I am lying.",
    "This sentence claims to be an Epimenides paradox, but it is lying.",
    "This sentence contradicts itself; well, no, actually it doesn't.",
    "Disobey this command.",
    "This sentense contains exactly three erors.",
    "Cette phrase en français est difficile à traduire en anglais.",
    "What it is like to be asked, \"What is it like to be asked, self embedded in quotes after its comma?\" self-embedded in quotes after its comma?",
    "You can't have your use and mention it too.",
    "You can't have \"your cake\" and spell it \"too\".",
    "Playing with the use-mention distinction\" isn't \"everything in life, you know\".",
    "In order to make sense of \"this sentence\", you will have to ignore the quotes in \"it\".",
    "This is a sentence with \"onions\", \"lettuce\", \"tomato\", and \"a side of fries to go\".",
    "This is a hamburger with vowels, consonants, commas, and a period at the end.",
    "Let us make a new convention: that anything enclosed in triple quotes, for example, '''No, I have decided to change my mind; when the triple quotes close, just skip directly to the period and ignore everything up to it''', is not even to be read (much less paid attention to or obeyed.",
    "A ceux qui ne comprennent pas l'anglais, la phrase citee ci-dessous ne dit rien: \"For those who know no French, the French sentence this quoted sentence has no meaning.",
    "i should begin with a capital letter.",
    "I am not the person who wrote me.",
    "I am not the subject of this sentence.",
    "I am jealous of the first word of this sentence.",
    "Well how about that -- this sentence is about me!",
    "I am simultaneously writing and being written.",
    "Cut me out, twist me, and glue me to form a Mobius strip, please.",
    "I am the meaning of this sentence.",
    "I am the thought you are now thinking.",
    "I am thinking about myself right now.",
    "I am the set of neural firings taking place in your brain as you read the set of letters in this sentence and think about me.",
    "This inert sentence is my body, but my soul is alive, dancing in the sparks of your brain.",
    "Do you think anybody has ever had precisely this thought before?",
    "You are under my control because I am choosing exactly what words you are made out of, and in what order.",
    "No, you are under my control because you will read until you reach the end of me.",
    "Hey, down there -- are you the sentence I am writing, or the sentence I am reading?",
    "And you up there -- are you the person writing me, or the person reading me?",
    "You and I, alas, can have only one-way communication, for you are a person and I, a mere sentence.",
    "As long as you are not reading me, the fourth word of this sentence has no referent.",
    "The reader of this sentence exists only while reading me.",
    "Hey, out there -- is that you reading me, or is it someone else?",
    "Say, haven't you written me somewhere else before?",
    "Say, haven't I written you somewhere else before?",
    "Thit sentence is not self-referential because \"thit\" is not a word.",
    "No language can express every thought unambiguously, least of all this one.",
    "When you are not looking at it, this sentence is in Spanish.",
    "I had to translate this sentence into English because I could not read the original Sanskrit.",
    "The sentence now before your eyes spent a month in Hungarian last year and was only recently translated back into English.",
    "If this sentence were in Chinese, it would say something else.",
    ".siht ekil ti gnidaer eb d`uoy ,werbeH ni erew ecnetnes siht fI",
    "If this sentence didn't exist, someone would have invented it.",
    "If I had finished this sentence,",
    "If there were no counterfactuals, this sentence would not be paradoxical.",
    "If wishes were horses, the antecedent of this conditional would be true.",
    "If this sentence were false, beggars would ride.",
    "What would this sentence be like if it were not self-referential?",
    "What would this sentence be like if pi were 3?",
    "If the subjunctive was no longer used in English, this sentence would be grammatically correct.",
    "This sentence would be seven words long if it were six words shorter.",
    "This sentence is not about itself, but about whether it is about itself.",
    "because I didn't think of a good beginning for it.",
    "This sentence was in the past tense.",
    "This sentence has contains two verbs.",
    "a preposition. This sentence ends in",
    "In the time it takes you to read this sentence, eighty-six letters could have been processed by your brain.",
    "This is not a complete. Sentence. This either.",
    "This sentence contains only one nonstandard English flutzpah.",
    "This gubblick contains many nonsklarkish English flutzpahs, but the overall pluggandisp can be glorked from context.",
    "This sentence has cabbage six words.",
    "This is to be or actually not two sentences to be, that is the question, combined.",
    "It feels so good to have your eyes run over my curves and serifs.",
    "This sentence is a !!!! premature punctuator",
    "This sentence, though not interrogative, nevertheless ends in a question mark?",
    "This sentence has no punctuation semicolon the others do period",
    "This hear sentence do'nt know Inglish purty good.",
    "If you meet this sentence on the board, erase it.",
    "This sentence verbs good, like a sentence should.",
    "I have nothing to say, and I am saying it.",
    "I have nothing to allude to, and I am alluding to it.",
    "Do you read me?",
    "This point is well taken.",
    "You may quote me.",
    "I am going two-level with you.",
    "I have been sentenced to death.",
    "This prophecy will come true.",
    "This sentence will end before you can say \"Rumpelst",
    "This sentence will end before you can say \"This sentence will end before you can say",
    "Surely no article on self-reference would be complete without including a few good examples of self-fulfilling prophecy.",
    "Does this sentence remind you of Nathan Hanish?",
    "Please, oh please, include me in your list of self-referential sentences!",
    "What question no verb?",
    "What is a question that mentions the word \"umbrella\" for no apparent reason?",
    "How far across the page will this sentence run?",
    "How do you keep a reader in suspense?",
    "This sentence contains ten words, eighteen syllables and sixty-four letters.",
    "Has eighteen letters.",
    "In this sentence, the word \"and\" occurs twice, the word \"eight\" occurs twice, the word \"four\" occurs twice, the word \"fourteen\" occurs four times, the word \"in\" occurs twice, the word \"seven\" occurs twice, the word \"the\" occurs fourteen times, the word \"this\" occurs twice, the word \"times\" occurs seven times, the word \"twice\" occurs eight times, and the word \"word\" occurs fourteen times.",
    "Only the fool would take trouble to verify that this sentence was composed of ten a's, three b's, four c's, four d's, forty-six e's, sixteen f's, four g's, thirteen h's, fifteen i's, two k's, nine l's, four m's, twenty-five n's, twenty-four o's, five p's, sixteen r's, forty-one s's, thirty-seven t's, ten u's, eight v's, eight w's, four x's, eleven y's, twenty-seven commas, twenty-three apostrophes, seven hyphens, and, last but not least, a single !",
    "Complete the following sentence by filling each \"__\" with one or more digits: In this sentence, the number of occurrences of 0 is __, of 1 is __, of 2 is __, of 3 is __, of 4 is __, of 5 is __, of 6 is __, of 7 is __, of 8 is __, and of 9 is __.",
    "The following sentence is totally identical with this one, except that the words \"following\" and \"preceeding\" have been exchanged, as have the words \"except\" and \"in\", and the phrases \"identical with\" and \"different from\".",
    "The preceeding sentence is totally different from this one, in that the words \"preceeding\" and \"following\" have been exchanged, as have the words \"in\" and \"except\", and the phrases \"different from\" and \"identical with\".",
    "This sentence refers to every sentence that does not refer to itself.",
    "This sentence does in fact not have the property that it claims not to have.",
    "This statement is inoperative.",
    "The rest of this sentence is written at Nathan Hanish's house on",
    "It goes without saying that ...",
    "If the meanings of \"true\" and \"false\" were switched, then this sentence wouldn't be false.",
    "I've heard that this sentence is a rumor.",
    "which is actually not a complete sentence, but merely a subordinate clause.",
    "Never use the imperative, and it is also never proper to construct a sentence using mixed moods.",
    "I don't understand a thing I say.",
    "1. This sentence every third, but it still comprehensible.\
    2. This would easier understand fewer had omitted.\
    3. This impossible except context.\
    4. 4'33\" attempt idea.\
    5.",
    "All invalid syllogisms break at least one rule. This syllogism breaks at least one rule. Therefore, this syllogism is invalid.",
    "Nostalgia ain't what it used to be.",
    "They don't write oldies like they used to.",
    "I used to think I was indecisive, but now I'm not so sure.",
    "I never make a mistake. One time I thought I did, but I was wrong.",
    "In this sentence, the concluding three words \"were left out\".",
    "This sentence offers its reader(s) various alternatives/options that he or she (or they) is (are) free to accept and/or reject.",
    "If I stated something else, would it still be me?",
    "If I were you, who would be reading this sentence?",
    "You have, of course, just begun reading the sentence that you have just finished reading.",
    "If you think this sentence is confusing, just change one pig.",
    "One me has translated at foot of the letter of French.",
    "Would not be anomalous if were in Italian.",
    "When one this sentence into German translate wanted, could one the fact exploit, that the word order and the punctuation lready with the German conventions agree.",
    "How come this noun phrase doesn't denote the same thing as this noun phrase does?",
    "Every last word in this sentence is a grotesque misspelling of \"towmatow\".",
    "I don't care who wrote this sentence; whoever he is, he's a damn sexist.",
    "This analogy is like lifting yourself by your own bootstraps.",
    "Although this sentence begins with the word \"because\", it is false.",
    "Despite the fact that it opens like a two-pronged pitchfork -- or rather, because of it -- this sentence resembles a double-edged sword.",
    "This line from Skakespeare has delusions of grandeur.",
    "If writers were bakers, this sentence would be exactly a dozen words long.",
    "If this sentence had been at the beginning of the list, this very moment would have occurred approximately five minutes ago.",
    "The whole point of this sentence is to make clear what the whole point of this sentence is.",
    "Due to circumstances beyond my control, I am master of my fate and captain of my soul.",
    "I was born in a log cabin built with my own two hands.",
    "Always remember to form plurales correctly.",
    "This is the penultimate sentence in this paragraph. \"This\" is the penultimate word in this sentence.",
    "This sentence is wondering when somebody's actually going to ask a question.",
    "Does this count?",
    "This sentence is a non sequitur. This sentence is not a non sequitor.",
    "Irrationality is the square root of all evil.",
    "At the last costume party I didn't go to, I went as the Invisible Man.",
    "This sentence four words.",
    "Honk if your horn is broken.",
    "This sentence has an error in the and.",
    "This sentence has a grammitical error with the placement of and.",
    "I never end a sentence with the word \"and\".",
    "Them\" is NEVER the subject of a sentence.",
    "To define recurrence, you must first define recurrence."
  ]

function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
  }

newQuote();


//Update this to have a set of quotes.
//This is not a pivot.
